# Generated by Django 3.2.5 on 2021-08-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='code',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='form',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='form',
            name='text_color',
        ),
    ]
