# Generated by Django 3.2.5 on 2021-08-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_form_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
