# Generated by Django 3.2.5 on 2021-08-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_choice_choices_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Options',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='choices',
        ),
        migrations.AddField(
            model_name='questions',
            name='options',
            field=models.ManyToManyField(related_name='options', to='core.Options'),
        ),
    ]
