# Generated by Django 3.2.5 on 2021-08-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210807_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='allow_view_score',
        ),
        migrations.RemoveField(
            model_name='form',
            name='authenticated_responder',
        ),
        migrations.RemoveField(
            model_name='form',
            name='collect_email',
        ),
        migrations.RemoveField(
            model_name='form',
            name='confirmation_message',
        ),
        migrations.RemoveField(
            model_name='form',
            name='edit_after_submit',
        ),
        migrations.RemoveField(
            model_name='form',
            name='is_quiz',
        ),
    ]
