# Generated by Django 3.2.5 on 2021-08-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210808_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_to',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='answer_key',
            new_name='key',
        ),
    ]
