# Generated by Django 3.2.5 on 2021-08-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210808_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='response',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='responder',
        ),
    ]
