# Generated by Django 3.2.5 on 2021-08-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210808_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='score',
        ),
    ]
