# Generated by Django 3.2.5 on 2021-08-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210808_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
