# Generated by Django 3.2.5 on 2021-08-12 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_responses_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.questions'),
        ),
        migrations.AlterField(
            model_name='form',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='form',
            name='questions',
            field=models.ManyToManyField(to='core.Questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='options',
            field=models.ManyToManyField(to='core.Options'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='answer',
            field=models.ManyToManyField(to='core.Answer'),
        ),
        migrations.AlterField(
            model_name='responses',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.form'),
        ),
    ]
